
Vagrant.configure("2") do |config|
  
  config.vm.box = "ubuntu/focal64"

  
  config.vm.network "private_network", ip: "192.168.56.12"

  
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"  # Asigna 2gb de memoria RAM
    vb.name = "PC5"  # Nombre de la VM
    vb.cpus = 2 
    vb.gui = false  # Desactiva la GUI de VirtualBox
    vb.customize ["modifyvm", :id, "--uartmode1", "disconnected"]  # Personalización de puerto serie
  end

  # Sincronizar la carpeta raíz (que contiene site.yml)
  config.vm.synced_folder "../", "/project"
  # Aprovisionamiento con Ansible
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "/project/site.yml"  # Ruta al playbook de Ansible
    ansible.extra_vars = { ansible_python_interpreter: "/usr/bin/python3" }
  end
  
end
